/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f4xx.h"

#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "timers.h"

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "usart_driver_hal.h"
#include "gpio_driver_hal.h"
#include "pll_driver_hal.h"
#include "exti_driver_hal.h"

# define STACK_SIZE 200
// definicion de variables del sistema
uint32_t SystemCoreClock = 100E6;
PLL_Config_t pllHandler = {0};

//USART
GPIO_Handler_t handlerPinTX		= {0};
GPIO_Handler_t handlerPinRX		= {0};
USART_Handler_t usart1Comm		= {0};
uint8_t usartData = 0;

/* Perifericos del sistema */
GPIO_Handler_t led_state = {0};
GPIO_Handler_t user_button = {0};
EXTI_Config_t exti_btn_Handler = {0};

/* Declaramos algunas variables propias del FreeRTOS */
BaseType_t xReturned;
TaskHandle_t xHandlerTask_Led = NULL;
TaskHandle_t xHandlerTask_Btn = NULL;

void vTask_Blink_Led(void * pvParameters);
void vTaskTwo(void * pvParameters);

/*  Cabeceras de las funciones del programa */
void initSystem(void);

/*	FUNCION QUE INICIALIZA EL USART 2 PARA COMUNICAR CON SYSTEM VIEW*/
extern void SEGGER_UART_init(uint32_t);
extern void vTask_Menu(void *pvParameters);
extern void vTask_Print(void *pvParameters);
extern void vTask_Commands(void *pvParameters);

TaskHandle_t xHandlerTask_MENU = NULL;
TaskHandle_t xHandlerTask_PRINT = NULL;
TaskHandle_t xHandlerTask_COMMANDS = NULL;

QueueHandle_t	xQueue_Print;
QueueHandle_t	xQueue_InputData;
/*
 * FUNCIÓN PRINCIPAL DEL PROGRAMA
 */
int main(void)
{

	/* Activamos la unidad de punto flotante (FPU) */
	SCB->CPACR    |= (0xF << 20);

	/* Activamos del contador de Ticks */
	DWT->CTRL    |= (1 << 0);

	/* Inicializamos el sistema */
	initSystem();


	/*Necesario para el SEGGER*/
//	vInitPrioGroupValue();

	/* Configuramos le puerto pra trabaar ocn SEGGER*/
//	SEGGER_UART_init(500E3);


	/* Primero configuramos */
//	SEGGER_SYSVIEW_Conf();
	/* Despues activamos el sistema */

	/*removemos al trabajar con el USART ya que el archivo hace esa configuración */
	//SEGGER_SYSVIEW_Start();


    xReturned = xTaskCreate(
    				vTask_Print,       		/* Function that implements the task. */
                    "Task-Print",        		/* Text name for the task. */
                    STACK_SIZE,      			/* Stack size in words, not bytes. */
                    NULL,    	/* Parameter passed into the task. */
                    2,							/* Priority at which the task is created. */
                    &xHandlerTask_PRINT );	/* Used to pass out the created task's handle. */

    configASSERT(xReturned == pdPASS);


    xReturned = xTaskCreate(
                    vTask_Commands,       			/* Function that implements the task. */
                    "Task-Commands",          			/* Text name for the task. */
                    STACK_SIZE,      			/* Stack size in words, not bytes. */
                    NULL,	/* Parameter passed into the task. */
                    2,							/* Priority at which the task is created. */
                    &xHandlerTask_COMMANDS );     		/* Used to pass out the created task's handle. */

    configASSERT(xReturned == pdPASS);


    xReturned = xTaskCreate(
                    vTask_Menu,       			/* Function that implements the task. */
                    "Task-Menu",          			/* Text name for the task. */
                    STACK_SIZE,      			/* Stack size in words, not bytes. */
                    NULL,	/* Parameter passed into the task. */
                    2,							/* Priority at which the task is created. */
                    &xHandlerTask_MENU );     		/* Used to pass out the created task's handle. */

    configASSERT(xReturned == pdPASS);



    //Creando las queue
    xQueue_InputData = xQueueCreate(10,sizeof(char));//manea caracteres individuales
    configASSERT(xQueue_InputData !=NULL); //verificamos que se haya creado la queue

    xQueue_Print = xQueueCreate(10,sizeof(size_t));//manea caracteres individuales
    configASSERT(xQueue_InputData !=NULL); //verificamos que se haya creado la queue





    //SEGGER_SYSVIEW_PrintfTarget("Starting the scheduler...");
    //STart the created tasks running
    vTaskStartScheduler();

    /* Loop forever */
	while(1){
		// Si llegamos aqui algo salio mal
	}
}


// Funcion para inicializar el sistema+
void initSystem(void){


	systemClock_100MHz(&pllHandler);
	RCC->CR &= ~(RCC_CR_HSITRIM); // Limpiamos el registro
	RCC->CR |= (11 << RCC_CR_HSITRIM_Pos); // Numero para calibrar POR DEFECTO ESTABA EN 15!!!!!

	// Configuramos el led de estado
	led_state.pGPIOx 						= GPIOA;
	led_state.pinConfig.GPIO_PinNumber		= PIN_5;
	led_state.pinConfig.GPIO_PinMode 		= GPIO_MODE_OUT;
	led_state.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_LOW;
	led_state.pinConfig.GPIO_PinOutputType 	= GPIO_OTYPE_PUSHPULL;
	led_state.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;

	// Cargamos la configuracion del pin led_state
	gpio_Config(&led_state);

	// Apagamos el led
	gpio_WritePin(&led_state, RESET);


	// Configuramos el boton con EXTI
	user_button.pGPIOx 							= GPIOC;
	user_button.pinConfig.GPIO_PinNumber		= PIN_13;
	user_button.pinConfig.GPIO_PinMode 			= GPIO_MODE_IN;
	user_button.pinConfig.GPIO_PinPuPdControl 	= GPIO_PUPDR_NOTHING;

	// Cargamos la configuracion del pin led_state
	gpio_Config(&user_button);

	exti_btn_Handler.pGPIOHandler				= &user_button;
	exti_btn_Handler.edgeType					= EXTERNAL_INTERRUPT_RISING_EDGE;
	exti_btn_Handler.priority					= e_EXTI_PRIORITY_6;

	//exti_config_Int_Priority(&exti_btn_Handler, e_EXTI_PRIORITY_6);
	exti_Config(&exti_btn_Handler);

	/* ==================================== Configurando los USART =============================================*/
	handlerPinTX.pGPIOx										= GPIOA;
	handlerPinTX.pinConfig.GPIO_PinNumber					= PIN_2;
	handlerPinTX.pinConfig.GPIO_PinMode						= GPIO_MODE_ALTFN;
	handlerPinTX.pinConfig.GPIO_PinOutputSpeed				= GPIO_OSPEED_HIGH;
	handlerPinTX.pinConfig.GPIO_PinAltFunMode				= AF7;
	gpio_Config(&handlerPinTX);

	handlerPinRX.pGPIOx										= GPIOA;
	handlerPinRX.pinConfig.GPIO_PinNumber					= PIN_3;
	handlerPinRX.pinConfig.GPIO_PinMode						= GPIO_MODE_ALTFN;
	handlerPinRX.pinConfig.GPIO_PinAltFunMode				= AF7;
	gpio_Config(&handlerPinRX);

	usart1Comm.ptrUSARTx									= USART2;
	usart1Comm.USART_Config.baudrate						= USART_BAUDRATE_19200_100MHz;
	usart1Comm.USART_Config.datasize						= USART_DATASIZE_8BIT;
	usart1Comm.USART_Config.parity							= USART_PARITY_NONE;
	usart1Comm.USART_Config.stopbits						= USART_STOPBIT_1;
	usart1Comm.USART_Config.mode							= USART_MODE_RXTX;
	usart1Comm.USART_Config.enableIntRX						= USART_RX_INTERRUPT_ENABLE;
	usart1Comm.USART_Config.enableIntTX						= USART_TX_INTERRUPT_DISABLE;
	usart_Config(&usart1Comm);
	usart_Config_Int_Priority(&usart1Comm, e_USART_PRIORITY_6);
}




void usart2_RxCallback(void){
	usartData = usart2_getRxData();

	BaseType_t xHigherPriorityTasWoken;
	(void ) xHigherPriorityTasWoken;

	xHigherPriorityTasWoken = pdFALSE;

	xReturned = xQueueIsQueueFullFromISR(xQueue_InputData);

	if(xReturned != pdTRUE){
		xQueueSendToBackFromISR(xQueue_InputData, (void*) &usartData, NULL);
	}
	else{
		//queue is FULL
		if(usartData == '#'){
			xQueueReceiveFromISR(xQueue_InputData, (void*)&usartData, NULL);
			//xQueueSendToBackFromISR(xQueue_InputData,(void*));
		}
	}



}

