/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f4xx.h"

#include "FreeRTOS.h"
#include "task.h"

#include <stdint.h>
#include <stdio.h>

#include "gpio_driver_hal.h"
#include "pll_driver_hal.h"
#include "exti_driver_hal.h"

# define STACK_SIZE 200
// definicion de variables del sistema
uint32_t SystemCoreClock = 100E6;
PLL_Config_t pllHandler = {0};

/* Perifericos del sistema */
GPIO_Handler_t led_state = {0};
GPIO_Handler_t user_button = {0};
EXTI_Config_t exti_btn_Handler = {0};

/* Declaramos algunas variables propias del FreeRTOS */
BaseType_t xReturned;
TaskHandle_t xHandlerTask_Led = NULL;
TaskHandle_t xHandlerTask_Btn = NULL;

void vTask_Blink_Led(void * pvParameters);
void vTaskTwo(void * pvParameters);

/*  Cabeceras de las funciones del programa */
void initSystem(void);

/*	FUNCION QUE INICIALIZA EL USART 2 PARA COMUNICAR CON SYSTEM VIEW*/
extern void SEGGER_UART_init(uint32_t);


/*
 * FUNCIÓN PRINCIPAL DEL PROGRAMA
 */
int main(void)
{

	/* Activamos la unidad de punto flotante (FPU) */
	SCB->CPACR    |= (0xF << 20);

	/* Activamos del contador de Ticks */
	DWT->CTRL    |= (1 << 0);

	/* Inicializamos el sistema */
	initSystem();


	/*Necesario para el SEGGER*/
	vInitPrioGroupValue();

	/* Configuramos le puerto pra trabaar ocn SEGGER*/
	SEGGER_UART_init(500E3);


	/* Primero configuramos */
	SEGGER_SYSVIEW_Conf();
	/* Despues activamos el sistema */

	/*removemos al trabajar con el USART ya que el archivo hace esa configuración */
	//SEGGER_SYSVIEW_Start();


    xReturned = xTaskCreate(
    				vTask_Blink_Led,       		/* Function that implements the task. */
                    "Task-Blinky",        		/* Text name for the task. */
                    STACK_SIZE,      			/* Stack size in words, not bytes. */
                    ("Led parpadeando"),    	/* Parameter passed into the task. */
                    2,							/* Priority at which the task is created. */
                    &xHandlerTask_Led );	/* Used to pass out the created task's handle. */

    configASSERT(xReturned == pdPASS);


    xReturned = xTaskCreate(
                    vTaskTwo,       			/* Function that implements the task. */
                    "Task-2",          			/* Text name for the task. */
                    STACK_SIZE,      			/* Stack size in words, not bytes. */
                    ("Hola mundo desde la Tarea-2"),	/* Parameter passed into the task. */
                    2,							/* Priority at which the task is created. */
                    &xHandlerTask2 );     		/* Used to pass out the created task's handle. */

    configASSERT(xReturned == pdPASS);



    SEGGER_SYSVIEW_PrintfTarget("Starting the scheduler...");
    //STart the created tasks running
    vTaskStartScheduler();

    /* Loop forever */
	while(1){
		// Si llegamos aqui algo salio mal
	}
}


/*
 * Funciones locales del main
 */

//Funcion que gobierna la tarea 1
void vTask_Blink_Led(void * pvParameters) {

	BaseType_t notify_status = {0};
	uint8_t ctrl_led = 0;

	/*
	 * Todas las tareas contienen un loop infinito.
	 * Si la ejecución se sale del loop, algo salió mal.
	 */
	while(1){
		//printf("%s\n",(char*)pvParameters);


		// Si se recibe la notificación, se hace el blinky
		if(ctrl_led){
			change_state = !change_state;
			gpio_TooglePin(&led_state);
		}
		else{
			gpio_WritePin(&led_state, RESET);
		}

		notify_status = xTaskNotifyWait(0, 0, NULL, pdMS_TO_TICKS(250));

		if (notify_status == pdTRUE){
			//Para desactivar las interrupciones por un peuqueño instante
			portENTER_CRITICAL();
			ctrl_led = !ctrl_led;
			// las volvemos a activar
			portEXIT_CRITICAL();
		}
		//vTaskDelay( pdMS_TO_TICKS(250));
		//TaskYIELD();
	}
}


//Funcion que gobierna la tarea 2
void vTaskTwo(void * pvParameters) {

	// Variables locales
	uint8_t button_state = 0;
	uint8_t prev_button_state = 0;


	while(1){

		//printf("%s\n",(char*)pvParameters);
		button_state = gpio_ReadPin(&user_button);

		// Se entra en todo el ciclo cuando se cumple que el botón se presiona y se deja de presionar
		if(button_state){
			if(!prev_button_state){

				// Esta función envía la notificación al Handler de la tarea que maneja del Blinky
				xTaskNotify(xHandlerTask_Blinky_Led, 0, eNoAction);
			}
		}
		prev_button_state = button_state;

		vTaskDelay(pdMS_TO_TICKS(10));
	}
}


// Funcion para inicializar el sistema+
void initSystem(void){


	systemClock_100MHz(&pllHandler);
	RCC->CR &= ~(RCC_CR_HSITRIM); // Limpiamos el registro
	RCC->CR |= (11 << RCC_CR_HSITRIM_Pos); // Numero para calibrar POR DEFECTO ESTABA EN 15!!!!!

	// Configuramos el led de estado
	led_state.pGPIOx 						= GPIOA;
	led_state.pinConfig.GPIO_PinNumber		= PIN_5;
	led_state.pinConfig.GPIO_PinMode 		= GPIO_MODE_OUT;
	led_state.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_LOW;
	led_state.pinConfig.GPIO_PinOutputType 	= GPIO_OTYPE_PUSHPULL;
	led_state.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;

	// Cargamos la configuracion del pin led_state
	gpio_Config(&led_state);

	// Apagamos el led
	gpio_WritePin(&led_state, RESET);


	// Configuramos el boton con EXTI
	user_button.pGPIOx 							= GPIOC;
	user_button.pinConfig.GPIO_PinNumber		= PIN_13;
	user_button.pinConfig.GPIO_PinMode 			= GPIO_MODE_IN;
	user_button.pinConfig.GPIO_PinPuPdControl 	= GPIO_PUPDR_NOTHING;

	// Cargamos la configuracion del pin led_state
	gpio_Config(&user_button);

	exti_btn_Handler.pGPIOHandler				= &user_button;
	exti_btn_Handler.edgeType					= EXTERNAL_INTERRUPT_RISING_EDGE;
	exti_btn_Handler.priority					= e_EXTI_PRIORITY_6;

	//exti_config_Int_Priority(&exti_btn_Handler, e_EXTI_PRIORITY_6);
	exti_Config(&exti_btn_Handler);


}


void callback_ExtInt13(void){
	BaseType_t pxHigherPriorityTaskWoken;
	pxHigherPriorityTaskWoken = pdFALSE;
	// Esta es una funcion para el SEGGER SYSVIEW reconozca la interrupción
	traceISR_ENTER();
	// Notificamos la funcion del LED
	xTaskNotifyFromISR(xHandlerTask_Led,0,eNoAction,&pxHigherPriorityTaskWoken);
	//portYIELD_FROM_ISR(pxHigherPriorityTaskWoken);
	traceISR_EXIT();

}


