/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
#include "string.h"
#include <stdio.h>
#include <math.h>
#include "stm32f4xx.h"
//#include "stm32_assert.h"
#include "gpio_driver_hal.h"
#include "timer_driver_hal.h"
#include "usart_driver_hal.h"
#include "pwm_driver_hal.h"
#include "exti_driver_hal.h"
#include "systick_driver_hal.h"
#include "pll_driver_hal.h"

#include "mpu6050_driver.h"
#include "i2c_driver_hal.h"



// Se define un pin para el Blinky
GPIO_Handler_t stateLed = {0}; // PinA5PinA5


// Handler Timers
Timer_Handler_t Tim_Blinky = {0};
Timer_Handler_t Tim_Micros = {0};


// Handler para el PLL
PLL_Config_t pllHandler = {0};

// Handler Systick


/*
 * Variables globales
 */
uint32_t SystemCoreClock = 100E6;

//USART
GPIO_Handler_t handlerPinTX		= {0};
GPIO_Handler_t handlerPinRX		= {0};
USART_Handler_t usart2Comm		= {0};


char bufferMsg[128] = {0};
char bufferReceiver[64] = {0};
uint8_t rxData = 0;
uint8_t counterReception = 0;
uint8_t stringComplete = 0;

// Variables para los comandos
char cmd[64] = {0};
float firstParameter = 0;
float secondParameter = 0;
char lastString[64] = {0};

// Variables globales para el funcionamiento del robot
uint8_t defaultSpeed = 0;
uint8_t counterPeriodBlinky = 0;
uint8_t flagTimer = 0;

///////////////////////////////////////////////////////////////////////////////////////////////////////
I2C_Handler_t imuHandler = {0};
GPIO_Handler_t imuSDA = {0};
GPIO_Handler_t imuSCL = {0};


uint8_t rawAccel[6] = {0};
uint8_t rawGyro[6] = {0};
uint8_t rawTemp[6] = {0};


char bufferData[64] = "Accel ADXL345 testing...";
float accel[6] = {0};
float gyro[6] = {0};
float temp[6] = {0};








///////////////////////////////////////////////////////////////////////////////////////////////////////


// Funciones privadas
void initSystem(void);
void parseCommands(char  *ptrbufferReception);


/* ===== Función principal del programa ===== */
int main(void){

	SCB->CPACR |= 0xf<<20;

	// Configuramos el PLL para que el micro corra a 100MHz
//	systemClock_100MHz(&pllHandler);
//	systemClock_Output(); // el pin PC9 configurado como salida para leer la freq
//
//	RCC->CR &= ~(RCC_CR_HSITRIM); // Limpiamos el registro
//	RCC->CR |= (11 << RCC_CR_HSITRIM_Pos); // Numero para calibrar POR DEFECTO ESTABA EN 15!!!!!

	initSystem();
	config_SysTick_ms(HSI_CLOCK_CONFIGURED);
	/* 5. Generamos la condición Stop, para que el slave se detenga después de 1 byte */
//	delay_ms(1);
//	i2c_StopTransaction(&imuHandler);
	delay_ms(1);
	imuBegin(&imuHandler);
	delay_ms(1);
	imuBegin(&imuHandler);
	uint8_t WhoAmI = i2c_ReadSingleRegister(&imuHandler,WHO_AM_I);

	sprintf(bufferData, "WHOAMI = %u \n", WhoAmI);
	usart_WriteMsg(&usart2Comm, bufferData);

	setAccelRange(&imuHandler, ACCEL_RANGE_2_G);
	setGyroRange(&imuHandler, GYRO_RANGE_250_DEG);
	sprintf(bufferMsg, "Saludos terricolas, soy OPPY \n");
	usart_WriteMsg(&usart2Comm, bufferMsg);

	/* Loop forever */
	while (1) {

		if (flagTimer) {

			usart_WriteMsg(&usart2Comm, "Hola mundo\n");
			gpio_TooglePin(&stateLed);
			delay_ms(2000);
			gpio_TooglePin(&stateLed);
			delay_ms(2000);
			gpio_TooglePin(&stateLed);
			delay_ms(2000);
			gpio_TooglePin(&stateLed);

			usart_WriteMsg(&usart2Comm, "Cambiamos velocidad\n");

			delay_ms(500);
			gpio_TooglePin(&stateLed);
			delay_ms(500);
			gpio_TooglePin(&stateLed);
			delay_ms(500);
			gpio_TooglePin(&stateLed);

			usart_WriteMsg(&usart2Comm, "CUCHAU\n");

			delay_ms(100);
			gpio_TooglePin(&stateLed);
			delay_ms(100);
			gpio_TooglePin(&stateLed);
			delay_ms(100);
			gpio_TooglePin(&stateLed);

			readAccel(&imuHandler, accel);

			sprintf(bufferData, "AccelX = %.2f \n", accel[0]);
			usart_WriteMsg(&usart2Comm, bufferData);

			sprintf(bufferData, "AccelY = %.2f \n", accel[1]);
			usart_WriteMsg(&usart2Comm, bufferData);

			sprintf(bufferData, "AccelZ = %.2f \n", accel[2]);
			usart_WriteMsg(&usart2Comm, bufferData);
			flagTimer = 0;
		}

//	begin(&imuHandler);

	}
	return 0;


}	// Fin del main



// Función para configurar los periféricos iniciales del sistemas
void initSystem(void){



	// 1. ===== PUERTOS Y PINES =====
	/* Configurando el pin para el Blinky */
	stateLed.pGPIOx								= GPIOA;
	stateLed.pinConfig.GPIO_PinNumber			= PIN_5;	// PinA5
	stateLed.pinConfig.GPIO_PinMode				= GPIO_MODE_OUT;
	stateLed.pinConfig.GPIO_PinOutputType		= GPIO_OTYPE_PUSHPULL;
	stateLed.pinConfig.GPIO_PinOutputSpeed		= GPIO_OSPEED_MEDIUM;
	stateLed.pinConfig.GPIO_PinPuPdControl		= GPIO_PUPDR_NOTHING;
	gpio_Config(&stateLed);





	// 2. ===== TIMERS =====
	/* Configurando el Timer del Blinky */
	Tim_Blinky.pTIMx								= TIM2;
	Tim_Blinky.TIMx_Config.TIMx_Prescaler			= 16000;	// Genera incrementos de 1 ms. El micro está a 100MHz
	Tim_Blinky.TIMx_Config.TIMx_Period				= 500;		// De la mano con el pre-scaler, determina cuando se dispara una interrupción (1 s)
	Tim_Blinky.TIMx_Config.TIMx_mode				= TIMER_UP_COUNTER;	// El Timer cuante ascendente
	Tim_Blinky.TIMx_Config.TIMx_InterruptEnable		= TIMER_INT_ENABLE;	// Se activa la interrupción
	timer_Config(&Tim_Blinky);
	timer_SetState(&Tim_Blinky, TIMER_ON);




	// 5. ====== SYSTICK =====



	/* ==================================== Configurando los USART =============================================*/
	handlerPinTX.pGPIOx										= GPIOA;
	handlerPinTX.pinConfig.GPIO_PinNumber					= PIN_2;
	handlerPinTX.pinConfig.GPIO_PinMode						= GPIO_MODE_ALTFN;
	handlerPinTX.pinConfig.GPIO_PinAltFunMode				= AF7;
	gpio_Config(&handlerPinTX);

	handlerPinRX.pGPIOx										= GPIOA;
	handlerPinRX.pinConfig.GPIO_PinNumber					= PIN_3;
	handlerPinRX.pinConfig.GPIO_PinMode						= GPIO_MODE_ALTFN;
	handlerPinRX.pinConfig.GPIO_PinAltFunMode				= AF7;
	gpio_Config(&handlerPinRX);

	usart2Comm.ptrUSARTx									= USART2;
	usart2Comm.USART_Config.baudrate						= USART_BAUDRATE_19200;
	usart2Comm.USART_Config.datasize						= USART_DATASIZE_8BIT;
	usart2Comm.USART_Config.parity							= USART_PARITY_NONE;
	usart2Comm.USART_Config.stopbits						= USART_STOPBIT_1;
	usart2Comm.USART_Config.mode							= USART_MODE_RXTX;
	usart2Comm.USART_Config.enableIntRX						= USART_RX_INTERRUPT_ENABLE;
	usart2Comm.USART_Config.enableIntTX						= USART_TX_INTERRUPT_DISABLE;
	usart_Config(&usart2Comm);


	///////////////////////////////////////////////////////////////////////////////////////////////////////
	imuSDA.pGPIOx								= GPIOC;
	imuSDA.pinConfig.GPIO_PinNumber				= PIN_9;
	imuSDA.pinConfig.GPIO_PinMode				= GPIO_MODE_ALTFN;
	imuSDA.pinConfig.GPIO_PinOutputType			= GPIO_OTYPE_OPENDRAIN;
	imuSDA.pinConfig.GPIO_PinAltFunMode			= AF4;
	imuSDA.pinConfig.GPIO_PinPuPdControl		= GPIO_PUPDR_NOTHING;
	imuSDA.pinConfig.GPIO_PinOutputSpeed		= GPIO_OSPEED_FAST;
	gpio_Config(&imuSDA);

	imuSCL.pGPIOx								= GPIOA;
	imuSCL.pinConfig.GPIO_PinNumber				= PIN_8;
	imuSCL.pinConfig.GPIO_PinMode				= GPIO_MODE_ALTFN;
	imuSCL.pinConfig.GPIO_PinOutputType			= GPIO_OTYPE_OPENDRAIN;
	imuSCL.pinConfig.GPIO_PinAltFunMode			= AF4;
	imuSCL.pinConfig.GPIO_PinPuPdControl		= GPIO_PUPDR_PULLUP;
	imuSCL.pinConfig.GPIO_PinOutputSpeed		= GPIO_OSPEED_FAST;
	gpio_Config(&imuSCL);


	imuHandler.slaveAddress = MPU6050_ADDRESS; //105;
	imuHandler.ptrI2Cx		= I2C3;
	imuHandler.modeI2C		= I2C_MODE_SM;
	imuHandler.mainClock	= MAIN_CLOCK_16_MHz_FOR_I2C;
	imuHandler.maxI2C_SM	= I2C_MODE_SM_SPEED_100KHz_16MHz;

	i2c_Config(&imuHandler);


	///////////////////////////////////////////////////////////////////////////////////////////////////////

}


/*
 * Función para los comandos
 */
void parseCommands(char  *ptrbufferReception){

	sscanf(ptrbufferReception,"%s %f %f %s",cmd,&firstParameter,&secondParameter,lastString);
	//Comando para solicitar ayuda
	if(strcmp(cmd, "help") == 0){
		usart_WriteMsg(&usart2Comm, "Help Menu CMDS: \n");
		usart_WriteMsg(&usart2Comm, "1) Dir 0:forw / 1:back ; dutty(\%) \" Dir # # @\" \n");
		usart_WriteMsg(&usart2Comm, "1) Cuentas dutty(\%) \" Cuentas (#) @\" \n");

		usart_WriteMsg(&usart2Comm, "2) Spd \%leftM 		; \%rightM \" Spd # # @\" \n");
		usart_WriteMsg(&usart2Comm, "3) Rot 0:left 1:right  ; #turns  \" Rot # # @\" \n");
		usart_WriteMsg(&usart2Comm, "4) TestEncoders percDuttyCycle:left \" TestEncoders # @\" \n");

		usart_WriteMsg(&usart2Comm, "5) Test 0:left / 1:right; dutty   \" Test # # @\" \n");
		usart_WriteMsg(&usart2Comm, "1) Ajuste Cuentas (#) deltaDuty (float) @ \n");


		usart_WriteMsg(&usart2Comm, "6) Stop \" Stop @\" \n");
		usart_WriteMsg(&usart2Comm, "7) Resume \" Resume @\" \n");

	}









	else if (strcmp(cmd, "reset") == 0) {
		usart_WriteMsg(&usart2Comm, "PWR_MGMT_1 reset \n");

	}

	else{
		usart_WriteMsg(&usart2Comm, "Comando erroneo.\n Ingresa \"help @\" para ver la lista de comandos.\n");
	}


}

/* Callback de Timer 3 para el Blinky */
void Timer2_Callback(void){
//	gpio_TooglePin(&stateLed);
	counterPeriodBlinky++;
	// La bandera se levanta cada 500 ms
	flagTimer = 1;
}


/* Interrupciones por recepcion a traves de transmision serial */
void usart1_RxCallback(void){
	rxData = usart1_getRxData();

}


