/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
#include "string.h"
#include <stdio.h>
#include <math.h>
#include "stm32f4xx.h"
//#include "stm32_assert.h"
#include "gpio_driver_hal.h"
#include "timer_driver_hal.h"
#include "usart_driver_hal.h"
#include "pwm_driver_hal.h"
#include "exti_driver_hal.h"
#include "systick_driver_hal.h"
#include "pll_driver_hal.h"

#include "mpu6050_driver.h"
#include "i2c_driver_hal.h"



// Se define un pin para el Blinky
GPIO_Handler_t stateLed = {0}; // PinA5
GPIO_Handler_t stateLedBoard = {0}; // PinC5

// Pines para el motor Derecho
GPIO_Handler_t GPIO_Enb_R = {0};
GPIO_Handler_t GPIO_Dir_R = {0};
GPIO_Handler_t GPIO_PWM_R = {0};

// Pines para el motor Izquierdo
GPIO_Handler_t GPIO_Enb_L = {0};
GPIO_Handler_t GPIO_Dir_L = {0};
GPIO_Handler_t GPIO_PWM_L = {0};

// Pines para interrupciones EXTI
GPIO_Handler_t GPIO_Exti_R = {0};
GPIO_Handler_t GPIO_Exti_L = {0};

// Handler para el PLL
PLL_Handler_t pllHandler = {0};

// Handler PWM motores
PWM_Handler_t PWM_R = {0};
PWM_Handler_t PWM_L = {0};

// Estructura para la configuración de los EXTI
EXTI_Config_t Exti_R = {0};
EXTI_Config_t Exti_L = {0};


/*
 * Variables globales
 */
uint32_t SystemCoreClock = 100E6;
uint16_t counter_R = 0;
uint16_t counter_L = 0;

//USART
GPIO_Handler_t handlerPinTX		= {0};
GPIO_Handler_t handlerPinRX		= {0};
USART_Handler_t usart2Comm		= {0};


char bufferMsg[128] = {0};
char bufferReceiver[64] = {0};
uint8_t rxData = 0;
uint8_t counterReception = 0;
uint8_t stringComplete = 0;

// Variables para los comandos
char cmd[64] = {0};
float firstParameter = 0;
float secondParameter = 0;
char lastString[64] = {0};

// Contadores ruedas
// Variables globales para el funcionamiento del robot
uint8_t defaultSpeed = 0;
uint8_t counterPercDuty = 0;
uint8_t flagEncR = 0;
uint8_t flagEncL = 0;
uint8_t flagStop = 0;
uint8_t flagPeriod = 0;
uint8_t flagTimer = 0;


float diameterWheel = 51.78; // Diámetro en mm

float percDutyR = 0;
float percDutyL = 0;

// Variables globales del PID que va a solucionar los problemas capilares de Nerio

// Constantes de Tuning del PID
float kp, ki, kd = 0;
uint32_t currTime, prevTime = 0;
float prevError, devError, integralError = 0;
float deltaError, deltaTime = 0;
float u_PID = 0;


// Contadores
uint16_t counterBlinky = 0;
uint16_t counterIMU = 0;
uint32_t counterMicros = 0;

uint8_t periodBlinky = 0;

///////////////////////////////////////////////////////////////////////////////////////////////////////
I2C_Handler_t imuHandler = {0};
GPIO_Handler_t imuSDA = {0};
GPIO_Handler_t imuSCL = {0};

char bufferData[64] = "Accel MPU6050 testing...";

float accelData[3] = {0};


float gyroData[3] = {0};
float calibGyroData[3] = {0};

int nReadings = 300;
extern float offsetGyroData[3];

float temp = 0;


float previousGyroZ = 0.0;
float currentGyroZ = 0.0;


float yaw_gyro = 0.0;       // Ángulo calculado con el acelerómetro
float dt = 0.2;           // Intervalo de tiempo (10 ms)


///////////////////////////////////////////////////////////////////////////////////////////////////////

// Funciones privadas
void initSystem(void);
void parseCommands(char  *ptrbufferReception);
void forwardMove(float percDutyL, float percDutyR);
void backwardMove(float percDutyL, float percDutyR);
void notnamed(float *percDutyR, float *percDutyL, uint16_t counts , float deltaDuty);
void turnOff(void);
void turnOn(void);
void PID(uint16_t target, uint16_t measure);


void manageCounters(void);
void yawIntegral(void);


/* ===== Función principal del programa ===== */
int main(void){

	SCB->CPACR |= 0xf<<20;

	// Configuramos el PLL para que el micro corra a 100MHz
//	systemClock_100MHz(&pllHandler);
//	systemClock_Output(); // el pin PC9 configurado como salida para leer la freq

//	RCC->CR &= ~(RCC_CR_HSITRIM); // Limpiamos el registro
//	RCC->CR |= (11 << RCC_CR_HSITRIM_Pos); // Numero para calibrar POR DEFECTO ESTABA EN 15!!!!!

	initSystem();
	turnOff();
	sprintf(bufferMsg, "Saludos terrícolas, soy OPPY \n");
	usart_WriteMsg(&usart1Comm, bufferMsg);
	counterPercDuty = 0;
	percDutyR = 0;
	percDutyL = 0;
	flagEncR = 0;
	flagEncL = 0;
	flagPeriod = 0;
	flagTimer = 0;


	config_SysTick_ms(HSI_CLOCK_CONFIGURED);
	delay_ms(1);
	imuBegin(&imuHandler);
	delay_ms(1);
	imuBegin(&imuHandler);
	//verificamos WhoAmI
	uint8_t WhoAmI = imuWhoAmI(&imuHandler);
	sprintf(bufferData, "WHOAMI = %u \n", WhoAmI);
	usart_WriteMsg(&usart2Comm, bufferData);

	setAccelRange(&imuHandler, ACCEL_RANGE_2_G);
	setGyroRange(&imuHandler, GYRO_RANGE_500_DEG);
	setAccelDLPF(&imuHandler, DLPF_260HZ);

	sprintf(bufferMsg, "Saludos terricolas, soy OPPY \n");
	usart_WriteMsg(&usart2Comm, bufferMsg);

	usart_WriteMsg(&usart2Comm, "Please dont move the sensor. Calibration Starting...\n");
	sprintf(bufferMsg,"offset values  %.2f,%.2f,%.2f\n",offsetGyroData[0],offsetGyroData[1],offsetGyroData[2]);
	usart_WriteMsg(&usart2Comm, bufferMsg);
	gyroStaticCalibration(&imuHandler,nReadings);
	sprintf(bufferMsg,"offset values  %.2f,%.2f,%.2f\n",offsetGyroData[0],offsetGyroData[1],offsetGyroData[2]);
	usart_WriteMsg(&usart2Comm, bufferMsg);
	usart_WriteMsg(&usart2Comm, "Calib finished\n");

	/* Loop forever */
	while (1) {
		manageCounters();

		if (counterIMU > 20E3) {
			yawIntegral();
			counterIMU = 0;
		}

	}
	return 0;


}	// Fin del main



// Función para configurar los periféricos iniciales del sistemas
void initSystem(void){



	// 1. ===== PUERTOS Y PINES =====
	/* Configurando el pin para el Blinky */
	stateLed.pGPIOx								= GPIOA;
	stateLed.pinConfig.GPIO_PinNumber			= PIN_5;	// PinA5
	stateLed.pinConfig.GPIO_PinMode				= GPIO_MODE_OUT;
	stateLed.pinConfig.GPIO_PinOutputType		= GPIO_OTYPE_PUSHPULL;
	stateLed.pinConfig.GPIO_PinOutputSpeed		= GPIO_OSPEED_MEDIUM;
	stateLed.pinConfig.GPIO_PinPuPdControl		= GPIO_PUPDR_NOTHING;
	gpio_Config(&stateLed);

	/* Configurando el pin para el Blinky */
	stateLedBoard.pGPIOx							= GPIOC;
	stateLedBoard.pinConfig.GPIO_PinNumber			= PIN_5;	// PinA5
	stateLedBoard.pinConfig.GPIO_PinMode			= GPIO_MODE_OUT;
	stateLedBoard.pinConfig.GPIO_PinOutputType		= GPIO_OTYPE_PUSHPULL;
	stateLedBoard.pinConfig.GPIO_PinOutputSpeed		= GPIO_OSPEED_MEDIUM;
	stateLedBoard.pinConfig.GPIO_PinPuPdControl		= GPIO_PUPDR_NOTHING;
	gpio_Config(&stateLedBoard);


	// 2. ===== GPIOs =====
	/* Configurando el pin para el Enable del puente H */
	GPIO_Enb_R.pGPIOx							= GPIOC;
	GPIO_Enb_R.pinConfig.GPIO_PinNumber			= PIN_10;
	GPIO_Enb_R.pinConfig.GPIO_PinMode			= GPIO_MODE_OUT;
	GPIO_Enb_R.pinConfig.GPIO_PinOutputType		= GPIO_OTYPE_PUSHPULL;
	GPIO_Enb_R.pinConfig.GPIO_PinOutputSpeed	= GPIO_OSPEED_FAST;
	GPIO_Enb_R.pinConfig.GPIO_PinPuPdControl	= GPIO_PUPDR_NOTHING;
	gpio_Config(&GPIO_Enb_R);

	/* Configurando el pin para definir la dirección del motor DERECHO */
	GPIO_Dir_R.pGPIOx							= GPIOC;
	GPIO_Dir_R.pinConfig.GPIO_PinNumber			= PIN_12;
	GPIO_Dir_R.pinConfig.GPIO_PinMode			= GPIO_MODE_OUT;
	GPIO_Dir_R.pinConfig.GPIO_PinOutputType		= GPIO_OTYPE_PUSHPULL;
	GPIO_Dir_R.pinConfig.GPIO_PinOutputSpeed	= GPIO_OSPEED_FAST;
	GPIO_Dir_R.pinConfig.GPIO_PinPuPdControl	= GPIO_PUPDR_NOTHING;
	gpio_Config(&GPIO_Dir_R);

	/* Pin de salida del PWM para el motor derecho. Usa el Timer5 */
	GPIO_PWM_R.pGPIOx								= GPIOA;
	GPIO_PWM_R.pinConfig.GPIO_PinNumber				= PIN_0;
	GPIO_PWM_R.pinConfig.GPIO_PinMode				= GPIO_MODE_ALTFN;
	GPIO_PWM_R.pinConfig.GPIO_PinAltFunMode			= AF2;
	GPIO_PWM_R.pinConfig.GPIO_PinPuPdControl		= GPIO_PUPDR_NOTHING;
	GPIO_PWM_R.pinConfig.GPIO_PinOutputSpeed		= GPIO_OSPEED_FAST;
	gpio_Config(&GPIO_PWM_R);

	/* Configurando el pin para el Enable del puente H */
	GPIO_Enb_L.pGPIOx							= GPIOC;
	GPIO_Enb_L.pinConfig.GPIO_PinNumber			= PIN_11;
	GPIO_Enb_L.pinConfig.GPIO_PinMode			= GPIO_MODE_OUT;
	GPIO_Enb_L.pinConfig.GPIO_PinOutputType		= GPIO_OTYPE_PUSHPULL;
	GPIO_Enb_L.pinConfig.GPIO_PinOutputSpeed	= GPIO_OSPEED_FAST;
	GPIO_Enb_L.pinConfig.GPIO_PinPuPdControl	= GPIO_PUPDR_NOTHING;
	gpio_Config(&GPIO_Enb_L);

	/* Configurando el pin para definir la dirección del motor IZQUIERDO */
	GPIO_Dir_L.pGPIOx							= GPIOD;
	GPIO_Dir_L.pinConfig.GPIO_PinNumber			= PIN_2;
	GPIO_Dir_L.pinConfig.GPIO_PinMode			= GPIO_MODE_OUT;
	GPIO_Dir_L.pinConfig.GPIO_PinOutputType		= GPIO_OTYPE_PUSHPULL;
	GPIO_Dir_L.pinConfig.GPIO_PinOutputSpeed	= GPIO_OSPEED_FAST;
	GPIO_Dir_L.pinConfig.GPIO_PinPuPdControl	= GPIO_PUPDR_NOTHING;
	gpio_Config(&GPIO_Dir_L);

	/* Pin de salida del PWM para el motor izquierdo. Usa el Timer5 */
	GPIO_PWM_L.pGPIOx								= GPIOA;
	GPIO_PWM_L.pinConfig.GPIO_PinNumber				= PIN_1;
	GPIO_PWM_L.pinConfig.GPIO_PinMode				= GPIO_MODE_ALTFN;
	GPIO_PWM_L.pinConfig.GPIO_PinAltFunMode			= AF2;
	GPIO_PWM_L.pinConfig.GPIO_PinPuPdControl		= GPIO_PUPDR_NOTHING;
	GPIO_PWM_L.pinConfig.GPIO_PinOutputSpeed		= GPIO_OSPEED_FAST;
	gpio_Config(&GPIO_PWM_L);

	/* Pin del Encoder Derecho */
	GPIO_Exti_R.pGPIOx							= GPIOC;
	GPIO_Exti_R.pinConfig.GPIO_PinNumber		= PIN_1;
	GPIO_Exti_R.pinConfig.GPIO_PinMode			= GPIO_MODE_IN;
	gpio_Config(&GPIO_Exti_R);

	/* Pin del Encoder Izquierdo */
	GPIO_Exti_L.pGPIOx							= GPIOC;
	GPIO_Exti_L.pinConfig.GPIO_PinNumber		= PIN_3;
	GPIO_Exti_L.pinConfig.GPIO_PinMode			= GPIO_MODE_IN;
	gpio_Config(&GPIO_Exti_L);


	// 2. ===== TIMERS =====
	/* Configurando el Timer del Blinky */
	Tim_Blinky.pTIMx								= TIM2;
	Tim_Blinky.TIMx_Config.TIMx_Prescaler			= 100;	// Genera incrementos de 1 ms. El micro está a 100MHz
	Tim_Blinky.TIMx_Config.TIMx_Period				= 10;		// De la mano con el pre-scaler, determina cuando se dispara una interrupción (500ms)
	Tim_Blinky.TIMx_Config.TIMx_mode				= TIMER_UP_COUNTER;	// El Timer cuante ascendente
	Tim_Blinky.TIMx_Config.TIMx_InterruptEnable		= TIMER_INT_ENABLE;	// Se activa la interrupción
	timer_Config(&Tim_Blinky);
	timer_SetState(&Tim_Blinky, TIMER_ON);

	/* ==================================== PLL =============================================*/

	pllHandler.clkSpeed = FREQUENCY_100MHz;
	//Calibramos el clock
	RCC->CR &= ~RCC_CR_HSITRIM;			//Limpiamos el registro
	RCC->CR |= (12<<RCC_CR_HSITRIM_Pos); // Numero para calibrar POR DEFECTO ESTABA EN 15!!!!!
	configPLL(&pllHandler);

	/* ==================================== Configurando los USART =============================================*/
	handlerPinTX.pGPIOx										= GPIOA;
	handlerPinTX.pinConfig.GPIO_PinNumber					= PIN_2;
	handlerPinTX.pinConfig.GPIO_PinMode						= GPIO_MODE_ALTFN;
	handlerPinTX.pinConfig.GPIO_PinAltFunMode				= AF7;
	gpio_Config(&handlerPinTX);

	handlerPinRX.pGPIOx										= GPIOA;
	handlerPinRX.pinConfig.GPIO_PinNumber					= PIN_3;
	handlerPinRX.pinConfig.GPIO_PinMode						= GPIO_MODE_ALTFN;
	handlerPinRX.pinConfig.GPIO_PinAltFunMode				= AF7;
	gpio_Config(&handlerPinRX);

	usart2Comm.ptrUSARTx									= USART2;
	usart2Comm.USART_Config.baudrate						= USART_BAUDRATE_9600;
	usart2Comm.USART_Config.datasize						= USART_DATASIZE_8BIT;
	usart2Comm.USART_Config.parity							= USART_PARITY_NONE;
	usart2Comm.USART_Config.stopbits						= USART_STOPBIT_1;
	usart2Comm.USART_Config.mode							= USART_MODE_RXTX;
	usart2Comm.USART_Config.enableIntRX						= USART_RX_INTERRUPT_ENABLE;
	usart2Comm.USART_Config.enableIntTX						= USART_TX_INTERRUPT_DISABLE;
	usart_Config(&usart2Comm);


	// 3. ===== PWM =====
	/* Configurando el PWM para el motor DERECHO */
	PWM_R.ptrTIMx					= TIM5; // Timer5 usado para el PWM
	PWM_R.config.channel			= PWM_CHANNEL_1;
	PWM_R.config.prescaler			= 50E2; 	// 0.05 ms
	PWM_R.config.periodo			= 1000;		// 50 ms -> Frec. de 20 Hz
	PWM_R.config.percDuty			= 0;
	pwm_Config(&PWM_R);

	/* Configurando el PWM para el motor IZQUIERDO */
	PWM_L.ptrTIMx					= TIM5; // Timer5 usado para el PWM
	PWM_L.config.channel			= PWM_CHANNEL_2;
	PWM_L.config.prescaler			= 50E2; 	// 0.05 ms
	PWM_L.config.periodo			= 1000;		// 50 ms -> Frec. de 20 Hz
	PWM_L.config.percDuty			= 0;
	pwm_Config(&PWM_L);


	///////////////////////////////////////////////////////////////////////////////////////////////////////
	imuSDA.pGPIOx								= GPIOC;
	imuSDA.pinConfig.GPIO_PinNumber				= PIN_9;
	imuSDA.pinConfig.GPIO_PinMode				= GPIO_MODE_ALTFN;
	imuSDA.pinConfig.GPIO_PinOutputType			= GPIO_OTYPE_OPENDRAIN;
	imuSDA.pinConfig.GPIO_PinAltFunMode			= AF4;
	imuSDA.pinConfig.GPIO_PinPuPdControl		= GPIO_PUPDR_NOTHING;
	imuSDA.pinConfig.GPIO_PinOutputSpeed		= GPIO_OSPEED_FAST;
	gpio_Config(&imuSDA);

	imuSCL.pGPIOx								= GPIOA;
	imuSCL.pinConfig.GPIO_PinNumber				= PIN_8;
	imuSCL.pinConfig.GPIO_PinMode				= GPIO_MODE_ALTFN;
	imuSCL.pinConfig.GPIO_PinOutputType			= GPIO_OTYPE_OPENDRAIN;
	imuSCL.pinConfig.GPIO_PinAltFunMode			= AF4;
	imuSCL.pinConfig.GPIO_PinPuPdControl		= GPIO_PUPDR_PULLUP;
	imuSCL.pinConfig.GPIO_PinOutputSpeed		= GPIO_OSPEED_FAST;
	gpio_Config(&imuSCL);


	imuHandler.slaveAddress = MPU6050_ADDRESS; //105;
	imuHandler.ptrI2Cx		= I2C3;
	imuHandler.modeI2C		= I2C_MODE_SM;
	imuHandler.mainClock	= MAIN_CLOCK_100_MHz_FOR_I2C;

	i2c_Config(&imuHandler);


	///////////////////////////////////////////////////////////////////////////////////////////////////////

}


void manageCounters(void){
	if (counterBlinky > 50E3){//cada 500 ms revisamos los contadores

		gpio_TogglePin(&stateLed);//cambiamos el estado del led

		if (gpio_ReadPin(&stateLed)) {//si el pin esta en alto contamos
			if (periodBlinky > 10) {//contamos cada ciclo de encendido-apagado de led
				periodBlinky = 0;//reiniciamos la variable
			}
			periodBlinky++;//aumentamos el contador del periodo
		}

		counterBlinky = 0;

	}
}


void yawIntegral(void){
	readGyro(&imuHandler, gyroData);
	yaw_gyro += (gyroData[2] * dt)* (180.0/M_PI);

    // Corrección de los límites de yaw_gyro
//    if (yaw_gyro > 360.0) {
//        yaw_gyro -= 360.0;
//    } else if (yaw_gyro < 0.0) {
//        yaw_gyro += 360.0;
//    }

//	sprintf(bufferMsg,"gyro values  %.2f,%.2f,%.2f\n",gyroData[0],gyroData[1],gyroData[2]);
	sprintf(bufferMsg,"rate is  %.2f \t Yaw  %.2f\n",gyroData[2],yaw_gyro);
	usart_WriteMsg(&usart2Comm, bufferMsg);
}



/* Callback de Timer 3 para el Blinky */
void Timer2_Callback(void){
//	gpio_TogglePin(&stateLed);
	counterBlinky++;
	counterIMU++;
	counterMicros++;

}


/* Interrupciones por recepcion a traves de transmision serial */
void usart1_RxCallback(void){
	rxData = usart1_getRxData();

}


