/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f4xx.h"

#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "timers.h"

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "gpio_driver_hal.h"
#include "pll_driver_hal.h"
#include "exti_driver_hal.h"

# define STACK_SIZE 200
// definicion de variables del sistema
uint32_t SystemCoreClock = 100E6;
PLL_Config_t pllHandler = {0};

/* Perifericos del sistema */
GPIO_Handler_t led_state = {0};
GPIO_Handler_t user_button = {0};
EXTI_Config_t exti_btn_Handler = {0};

/* Declaramos algunas variables propias del FreeRTOS */
BaseType_t xReturned;
TaskHandle_t xHandlerTask_Led = NULL;
TaskHandle_t xHandlerTask_Btn = NULL;

void vTask_Blink_Led(void * pvParameters);
void vTaskTwo(void * pvParameters);

/*  Cabeceras de las funciones del programa */
void initSystem(void);

/*	FUNCION QUE INICIALIZA EL USART 2 PARA COMUNICAR CON SYSTEM VIEW*/
extern void SEGGER_UART_init(uint32_t);
extern void vTask_Menu(void *pvParameters);
extern void vTask_Print(void *pvParameters);
extern void vTask_Commands(void *pvParameters);

TaskHandle_t xHandlerTask_MENU = NULL;
TaskHandle_t xHandlerTask_PRINT = NULL;
TaskHandle_t xHandlerTask_COMMANDS = NULL;
/*
 * FUNCIÓN PRINCIPAL DEL PROGRAMA
 */
int main(void)
{

	/* Activamos la unidad de punto flotante (FPU) */
	SCB->CPACR    |= (0xF << 20);

	/* Activamos del contador de Ticks */
	DWT->CTRL    |= (1 << 0);

	/* Inicializamos el sistema */
	initSystem();


	/*Necesario para el SEGGER*/
//	vInitPrioGroupValue();

	/* Configuramos le puerto pra trabaar ocn SEGGER*/
//	SEGGER_UART_init(500E3);


	/* Primero configuramos */
//	SEGGER_SYSVIEW_Conf();
	/* Despues activamos el sistema */

	/*removemos al trabajar con el USART ya que el archivo hace esa configuración */
	//SEGGER_SYSVIEW_Start();


    xReturned = xTaskCreate(
    				vTask_Print,       		/* Function that implements the task. */
                    "Task-Print",        		/* Text name for the task. */
                    STACK_SIZE,      			/* Stack size in words, not bytes. */
                    ("Led parpadeando"),    	/* Parameter passed into the task. */
                    2,							/* Priority at which the task is created. */
                    &xHandlerTask_MENU );	/* Used to pass out the created task's handle. */

    configASSERT(xReturned == pdPASS);


    xReturned = xTaskCreate(
                    vTask_Commands,       			/* Function that implements the task. */
                    "Task-2",          			/* Text name for the task. */
                    STACK_SIZE,      			/* Stack size in words, not bytes. */
                    ("Hola mundo desde la Tarea-2"),	/* Parameter passed into the task. */
                    2,							/* Priority at which the task is created. */
                    &xHandlerTask_PRINT );     		/* Used to pass out the created task's handle. */

    configASSERT(xReturned == pdPASS);


    xReturned = xTaskCreate(
                    vTask_Menu,       			/* Function that implements the task. */
                    "Task-2",          			/* Text name for the task. */
                    STACK_SIZE,      			/* Stack size in words, not bytes. */
                    ("Hola mundo desde la Tarea-2"),	/* Parameter passed into the task. */
                    2,							/* Priority at which the task is created. */
                    &xHandlerTask_COMMANDS );     		/* Used to pass out the created task's handle. */

    configASSERT(xReturned == pdPASS);



    //SEGGER_SYSVIEW_PrintfTarget("Starting the scheduler...");
    //STart the created tasks running
    vTaskStartScheduler();

    /* Loop forever */
	while(1){
		// Si llegamos aqui algo salio mal
	}
}


// Funcion para inicializar el sistema+
void initSystem(void){


	systemClock_100MHz(&pllHandler);
	RCC->CR &= ~(RCC_CR_HSITRIM); // Limpiamos el registro
	RCC->CR |= (11 << RCC_CR_HSITRIM_Pos); // Numero para calibrar POR DEFECTO ESTABA EN 15!!!!!

	// Configuramos el led de estado
	led_state.pGPIOx 						= GPIOA;
	led_state.pinConfig.GPIO_PinNumber		= PIN_5;
	led_state.pinConfig.GPIO_PinMode 		= GPIO_MODE_OUT;
	led_state.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_LOW;
	led_state.pinConfig.GPIO_PinOutputType 	= GPIO_OTYPE_PUSHPULL;
	led_state.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;

	// Cargamos la configuracion del pin led_state
	gpio_Config(&led_state);

	// Apagamos el led
	gpio_WritePin(&led_state, RESET);


	// Configuramos el boton con EXTI
	user_button.pGPIOx 							= GPIOC;
	user_button.pinConfig.GPIO_PinNumber		= PIN_13;
	user_button.pinConfig.GPIO_PinMode 			= GPIO_MODE_IN;
	user_button.pinConfig.GPIO_PinPuPdControl 	= GPIO_PUPDR_NOTHING;

	// Cargamos la configuracion del pin led_state
	gpio_Config(&user_button);

	exti_btn_Handler.pGPIOHandler				= &user_button;
	exti_btn_Handler.edgeType					= EXTERNAL_INTERRUPT_RISING_EDGE;
	exti_btn_Handler.priority					= e_EXTI_PRIORITY_6;

	//exti_config_Int_Priority(&exti_btn_Handler, e_EXTI_PRIORITY_6);
	exti_Config(&exti_btn_Handler);


}


void callback_ExtInt13(void){
	BaseType_t pxHigherPriorityTaskWoken;
	pxHigherPriorityTaskWoken = pdFALSE;
	// Esta es una funcion para el SEGGER SYSVIEW reconozca la interrupción
	traceISR_ENTER();
	// Notificamos la funcion del LED
	xTaskNotifyFromISR(xHandlerTask_Led,0,eNoAction,&pxHigherPriorityTaskWoken);
	//portYIELD_FROM_ISR(pxHigherPriorityTaskWoken);
	traceISR_EXIT();

}


